const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
const {createPasskeyService}=require('../lib/passkey.cjs');
const RP='kkumjari-worship.vercel.app',ORIGIN='https://'+RP;
const sha=b=>crypto.createHash('sha256').update(b).digest();
/* tiny CBOR encoder for test fixtures */
function enc(v){const head=(m,n)=>n<24?Buffer.from([m<<5|n]):n<256?Buffer.from([m<<5|24,n]):Buffer.from([m<<5|25,n>>8,n&255]);
 if(Buffer.isBuffer(v))return Buffer.concat([head(2,v.length),v]);if(typeof v==='string'){const b=Buffer.from(v);return Buffer.concat([head(3,b.length),b])}
 if(typeof v==='number')return v>=0?head(0,v):head(1,-1-v);if(v instanceof Map)return Buffer.concat([head(5,v.size),...[...v].flatMap(([k,x])=>[enc(k),enc(x)])]);throw Error('enc')}
function fakeDb(){const docs=new Map();const doc=(c,id)=>({id,get:async()=>({exists:docs.has(c+'/'+id),data:()=>structuredClone(docs.get(c+'/'+id))}),set:async(v,o)=>{docs.set(c+'/'+id,o&&o.merge?{...(docs.get(c+'/'+id)||{}),...v}:structuredClone(v))},create:async v=>{if(docs.has(c+'/'+id))throw Object.assign(Error('ALREADY_EXISTS'),{code:6});docs.set(c+'/'+id,v)},delete:async()=>{docs.delete(c+'/'+id)}});
 return{docs,collection:c=>({doc:id=>doc(c,id),where:(f,op,val)=>({get:async()=>({docs:[...docs].filter(([k,v])=>k.startsWith(c+'/')&&v[f]===val).map(([k,v])=>({id:k.slice(c.length+1),data:()=>structuredClone(v)}))})})})}}
function device(){const {privateKey,publicKey}=crypto.generateKeyPairSync('ec',{namedCurve:'P-256'});const jwk=publicKey.export({format:'jwk'});const credId=crypto.randomBytes(16);let count=0;
 const cose=new Map([[1,2],[3,-7],[-1,1],[-2,Buffer.from(jwk.x,'base64url')],[-3,Buffer.from(jwk.y,'base64url')]]);
 const authData=(attested,rp=RP,flags=0x05)=>{const c=Buffer.alloc(4);c.writeUInt32BE(count++);const base=Buffer.concat([sha(Buffer.from(rp)),Buffer.from([flags|(attested?0x40:0)]),c]);if(!attested)return base;const l=Buffer.alloc(2);l.writeUInt16BE(credId.length);return Buffer.concat([base,Buffer.alloc(16),l,credId,enc(cose)])};
 return{id:credId.toString('base64url'),
  create(challenge,o={}){const cd=Buffer.from(JSON.stringify({type:'webauthn.create',challenge,origin:o.origin||ORIGIN}));return{id:credId.toString('base64url'),clientDataJSON:cd.toString('base64url'),attestationObject:enc(new Map([['fmt','none'],['attStmt',new Map()],['authData',authData(true,o.rp,o.flags)]])).toString('base64url')}},
  get(challenge,o={}){const cd=Buffer.from(JSON.stringify({type:'webauthn.get',challenge,origin:o.origin||ORIGIN}));const ad=authData(false,o.rp,o.flags);const sig=crypto.sign('sha256',Buffer.concat([ad,sha(cd)]),privateKey);return{id:o.id||credId.toString('base64url'),clientDataJSON:cd.toString('base64url'),authenticatorData:ad.toString('base64url'),signature:sig.toString('base64url')}}}}
function setup(){const db=fakeDb();const svc=createPasskeyService({db,auth:{createCustomToken:async uid=>'token-for-'+uid},secret:'test-secret'});return{db,svc}}
const actor={id:'u1',uid:'u1',name:'김찬양'},yes=async()=>true;
async function enroll(svc,dev,who=actor){const o=await svc.registerOptions(who);return svc.register(who,{ticket:o.ticket,...dev.create(o.challenge),label:'iPhone'},RP)}

test('register then sign in with Face ID issues a Firebase token for that account',async()=>{const{svc}=setup(),dev=device();const r=await enroll(svc,dev);assert.equal(r.credId,dev.id);const o=await svc.loginOptions({accountId:'u1'});assert.deepEqual(o.allow,[dev.id]);const out=await svc.login({ticket:o.ticket,...dev.get(o.challenge)},RP,yes);assert.equal(out.token,'token-for-u1');assert.equal(out.accountId,'u1')});
test('a challenge can be used only once (replay blocked)',async()=>{const{svc}=setup(),dev=device();await enroll(svc,dev);const o=await svc.loginOptions({accountId:'u1'});const a=dev.get(o.challenge);await svc.login({ticket:o.ticket,...a},RP,yes);await assert.rejects(svc.login({ticket:o.ticket,...a},RP,yes),/이미 사용한|복제/)});
test('wrong key, wrong site and missing biometric check are rejected',async()=>{const{svc}=setup(),dev=device(),other=device();await enroll(svc,dev);let o=await svc.loginOptions({accountId:'u1'});await assert.rejects(svc.login({ticket:o.ticket,...other.get(o.challenge,{id:dev.id})},RP,yes),/실패/);o=await svc.loginOptions({accountId:'u1'});await assert.rejects(svc.login({ticket:o.ticket,...dev.get(o.challenge,{origin:'https://evil.example'})},RP,yes),/사이트/);o=await svc.loginOptions({accountId:'u1'});await assert.rejects(svc.login({ticket:o.ticket,...dev.get(o.challenge,{flags:0x01})},RP,yes),/확인이 완료/)});
test('records written by someone else (without server signature) are ignored',async()=>{const{db,svc}=setup(),dev=device();const pub=crypto.generateKeyPairSync('ec',{namedCurve:'P-256'}).publicKey.export({format:'jwk'});await db.collection('passkeys').doc(dev.id).set({uid:'leader-uid',accountId:'leader-uid',alg:-7,jwk:pub,mac:'forged'});await assert.rejects(svc.loginOptions({accountId:'leader-uid'}),/등록돼 있지 않아요/)});
test('ticket for one account cannot log into another; unapproved accounts are blocked',async()=>{const{svc}=setup(),a=device(),b=device();await enroll(svc,a);await enroll(svc,b,{id:'u2',uid:'u2',name:'B'});const o=await svc.loginOptions({accountId:'u1'});await assert.rejects(svc.login({ticket:o.ticket,...b.get(o.challenge)},RP,yes),/등록되지 않은/);const o2=await svc.loginOptions({accountId:'u2'});await assert.rejects(svc.login({ticket:o2.ticket,...b.get(o2.challenge)},RP,async()=>false),/승인된 계정/)});
test('registration ticket is bound to the signed-in user; remove only deletes own device',async()=>{const{db,svc}=setup(),dev=device();const o=await svc.registerOptions(actor);await assert.rejects(svc.register({id:'u2',uid:'u2'},{ticket:o.ticket,...dev.create(o.challenge)},RP),/다른 계정/);await enroll(svc,dev);await svc.remove({id:'u2',uid:'u2'},{credId:dev.id});assert(db.docs.has('passkeys/'+dev.id));await svc.remove(actor,{credId:dev.id});assert(!db.docs.has('passkeys/'+dev.id))});
test('API handler: routes actions, uses site host as passkey domain, hides server errors',async()=>{const Module=require('node:module');const db=fakeDb();const origLoad=Module._load;const fake={MANAGER_EMAIL:'m@x',init(){},authenticate:async req=>{if(!req.headers.authorization)throw Object.assign(Error('로그인이 필요해요.'),{status:401});return actor},admin:{firestore:()=>Object.assign(db,{doc:p=>({get:async()=>({exists:true,data:()=>({status:'approved'})})})}),auth:()=>({createCustomToken:async uid=>'tok-'+uid,getUser:async()=>({email:'m@x'})})}};Module._load=function(req,...a){return /firebase\.cjs$/.test(req)?fake:origLoad.call(this,req,...a)};
 process.env.FIREBASE_SERVICE_ACCOUNT=JSON.stringify({private_key:'k'});delete require.cache[require.resolve('../api/passkey.js')];const handler=require('../api/passkey.js');
 const call=async(body,headers={})=>{let code=0,json=null;const res={setHeader(){},status(c){code=c;return this},json(j){json=j;return this}};await handler({method:'POST',headers:{host:RP,...headers},body},res);return{code,json}};
 const dev=device();let r=await call({action:'registerOptions'});assert.equal(r.code,401);r=await call({action:'registerOptions'},{authorization:'Bearer x'});assert.equal(r.code,200);assert.equal(r.json.rpId,RP);
 const reg=await call({action:'register',ticket:r.json.ticket,...dev.create(r.json.challenge)},{authorization:'Bearer x'});assert.equal(reg.code,200,JSON.stringify(reg.json));
 const lo=await call({action:'loginOptions',accountId:'u1'});assert.equal(lo.code,200);const li=await call({action:'login',ticket:lo.json.ticket,...dev.get(lo.json.challenge)});assert.equal(li.code,200,JSON.stringify(li.json));assert.equal(li.json.token,'tok-u1');
 const bad=await call({action:'nope'});assert.equal(bad.code,400);
 Module._load=origLoad});
test('management account is PIN-only: cannot register or sign in with Face ID',async()=>{const{svc}=setup(),dev=device();const mgr={id:'management',uid:'mgr-uid',name:'관리계정'};await assert.rejects(svc.registerOptions(mgr),/PIN으로만/);await assert.rejects(svc.loginOptions({accountId:'management'}),/PIN으로만/)});
