const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function env(){const c={Set,Map,Date,console,library:[],archive:[],trash:[],ldr:'test',BLOB:id=>'asset:'+id};vm.createContext(c);vm.runInContext(html.slice(html.indexOf('function kzKey('),html.indexOf('const KZ_KEYS=')),c);vm.runInContext(html.slice(html.indexOf('function scoreMeta'),html.indexOf('function fromData')),c);vm.runInContext(html.slice(html.indexOf('function libItems'),html.indexOf('const libMeta')),c);return c}
test('scripts parse',()=>{for(const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(m[1].trim())new vm.Script(m[1])});
test('old single pages remain valid; metadata survives reload',()=>{const c=env();const old=c.mkPage({name:'Old'});assert.equal(old.songId,'');assert.equal(old.pageNo,1);const p=c.mkPage({name:'Song',songId:'s',pageNo:3,oaid:'o3',seq:[{t:'V'}],marks:[{x:0.5}]});assert.equal(p.songId,'s');assert.equal(p.pageNo,3);assert.equal(p.seq[0].t,'V');assert.equal(p.marks.length,1)});
test('three pages are kept, same-title different groups stay separate',()=>{const c=env();c.library=[1,2,3].map(n=>({oaid:'p'+n,name:'목마른 사슴',songId:'one',pageNo:n}));c.library.push({oaid:'other',name:'목마른 사슴',songId:'two',pageNo:1});const list=c.libItems();assert.equal(list.length,4);assert.deepEqual(Array.from(list.filter(x=>x.songId==='one'),x=>x.pageNo).sort(),[1,2,3])});
test('group pages ordered together; lyrics song list counts group once',()=>{const c=env(),list=[{name:'A',songId:'a',pageNo:3},{name:'B'},{name:'A',songId:'a',pageNo:1},{name:'A',songId:'a',pageNo:2}];assert.deepEqual(Array.from(c.orderedScores(list),x=>x.pageNo||0),[1,2,3,0]);assert.deepEqual(Array.from(c.scoreSongNames(list)),['A','B']);assert.equal(c.scoreLabel(list[0]),'A · 3장')});
test('append uploads start at next page and bypass same-song title deduplication',async()=>{const c=env();let id=1;c.library=[{oaid:'first',name:'Song',songId:'s',pageNo:1}];Object.assign(c,{libMsg:'',view:'test',TO:async p=>p,claude:{use:async()=>({upload:async()=>({id:'new'+id++})})},FileReader:class{readAsDataURL(){this.result='image';this.onload()}},loadImg:async()=>({naturalWidth:100,naturalHeight:200}),shrinkOrig:async()=>({}),toast:()=>{},cfBox:()=>{},db:{doc:()=>({set:async()=>{}})}});vm.runInContext(html.slice(html.indexOf('async function libAdd'),html.indexOf('function closeImport')),c);await c.libAdd([{name:'Song.png'},{name:'Song2.png'}],{id:'s',name:'Song',startPage:2});assert.deepEqual(Array.from(c.library,x=>x.pageNo),[1,2,3]);assert(c.library.every(x=>x.songId==='s'))});
test('conti deletion retains every original and group metadata before deleting',async()=>{const c=env(),docs=new Map([['weeks/w',{scores:[{name:'Song',songId:'s',pageNo:1,oaid:'p1'},{name:'Song',songId:'s',pageNo:2,oaid:'p2'}]}]]);c.db={doc:k=>({get:async()=>({exists:docs.has(k),data:()=>docs.get(k)}),set:async v=>docs.set(k,v),delete:async()=>{assert(docs.has('library/p1'));assert(docs.has('library/p2'));docs.delete(k)}})};vm.runInContext(html.slice(html.indexOf('async function retainScoreOriginals'),html.indexOf('async function saveAll'))+html.slice(html.indexOf('async function toTrash'),html.indexOf('const trashPurging')),c);await c.toTrash('conti','w','weeks');assert.equal(docs.get('library/p2').pageNo,2);assert.equal(docs.get('library/p2').songId,'s');assert(!docs.has('weeks/w'))});

/* ---- 정리 작업(v25) 추가 검사 ---- */
function editorEnv(list){const c=env();c.pages=list.map(x=>({...x}));c.cur=0;c.canEdit=true;c.od=false;Object.assign(c,{drawList(){},drawStage(){},stat(){},sched(){},P(){return c.pages[c.cur]}});vm.runInContext(html.slice(html.indexOf('function scoreBlock'),html.indexOf('let lastRm=null')),c);return c}
const label=c=>Array.from(c.pages,p=>p.name+(p.songId?p.pageNo:''));
test('song order buttons move a multi-page song as one block',()=>{const c=editorEnv([{name:'A',songId:'a',pageNo:1},{name:'A',songId:'a',pageNo:2},{name:'B'},{name:'C',songId:'c',pageNo:1},{name:'C',songId:'c',pageNo:2}]);c.cur=1;c.movePage(1);assert.deepEqual(label(c),['B','A1','A2','C1','C2']);assert.equal(c.pages[c.cur].pageNo,2);c.movePage(1);assert.deepEqual(label(c),['B','C1','C2','A1','A2']);c.cur=0;c.movePage(-1);assert.deepEqual(label(c),['B','C1','C2','A1','A2'])});
test('dragging inside a song reorders its pages; dragging out moves the whole song',()=>{const c=editorEnv([{id:'p1',name:'A',songId:'a',pageNo:1},{id:'p2',name:'A',songId:'a',pageNo:2},{id:'p3',name:'A',songId:'a',pageNo:3},{id:'b',name:'B'}]);c.movePageTo(2,0);assert.deepEqual(Array.from(c.pages,p=>p.id),['p3','p1','p2','b']);assert.deepEqual(Array.from(c.pages.slice(0,3),p=>p.pageNo),[1,2,3]);assert.equal(c.pages.filter(p=>p.pageMetaDirty).length,3);c.movePageTo(3,1);assert.deepEqual(Array.from(c.pages,p=>p.id),['b','p3','p1','p2']);c.movePageTo(0,4);assert.deepEqual(Array.from(c.pages,p=>p.id),['p3','p1','p2','b'])});
test('song numbers in conti view count songs, not pages',()=>{const c=env();assert.deepEqual(Array.from(c.scoreSongNumbers([{songId:'a'},{songId:'a'},{name:'x'},{songId:'b'},{songId:'b'}])),[1,1,2,3,3])});
test('no large inline images; every referenced asset file exists',()=>{assert(!/data:image\/[a-z+]+;base64,[A-Za-z0-9+/=]{2000,}/.test(html),'inline base64 image found');const refs=new Set([...html.matchAll(/assets\/[\w.-]+\.(?:png|jpe?g|webp|gif|svg)/g)].map(m=>m[0]));assert(refs.size>0);for(const r of refs)assert(fs.existsSync(path.join(__dirname,'..',r)),'missing '+r)});

test('key: normalized, kept per page, same title with different keys stays separate in library',()=>{const c=env();
 assert.equal(c.kzKey('g'),'G');assert.equal(c.kzKey('F♯'),'F#');assert.equal(c.kzKey('bb'),'Bb');assert.equal(c.kzKey('Am'),'Am');assert.equal(c.kzKey('G키'),'G');assert.equal(c.kzKey('H'),'');
 assert.equal(c.mkPage({name:'목마른 사슴',key:'a'}).key,'A');
 c.library=[{oaid:'a1',name:'목마른 사슴',key:'A'},{oaid:'g1',name:'목마른 사슴',key:'G'},{oaid:'a2',name:'목마른사슴',key:'A'}];
 const l=c.libItems();assert.equal(l.length,2);assert.deepEqual(Array.from(l,x=>x.key).sort(),['A','G']);
 assert.equal(c.scoreLabel({name:'목마른 사슴',key:'G',songId:'s',pageNo:2}),'목마른 사슴 (G) · 2장');
});
